package dao

import groovy.sql.Sql

import java.sql.Connection

import org.bbs.models.Message

class MessageUtil {
	int pageSize=5;
	def dbMaps=[url:"jdbc:derby://localhost:1527/bbs;create=true",driver:"org.apache.derby.jdbc.ClientDriver"]
		def initTables(){
			Sql sql=Sql.newInstance(dbMaps);
			sql.execute('''
				create table tbl_message(id BIGINT GENERATED by default as IDENTITY,
				message varchar(500),
				author varchar(20),
				postTime timestamp
				)
			
			''')
			
		}
		
		/**
		 * 
		 * @param message
		 * @return
		 */
		def save(Message message){
			
			Sql sql=Sql.newInstance(dbMaps);
			sql.executeInsert("insert into tbl_message (message,author,postTime) values($message.message,$message.author,$message.postTime)").size()>0? 1: 0
			
		}
		def List<Message> listByPage(int page){
			Sql sql=Sql.newInstance(dbMaps)
		
			def totalCount=sql.rows("select id from tbl_message").size()
			if(totalCount/pageSize<page){page=totalCount/pageSize}
			if(page<0)page=0;
		
			int start=(page*pageSize)+1;
			int end=(start+pageSize)-1;
			
		
			
			def s="select * from (select row_number() over() as rownum,tbl_message.* from tbl_message) as TR where  rownum>=$start and rownum <=$end"
			
			
			List<Message> list=new ArrayList();
			 sql.rows(s).each {
				Message msg= new Message(it.id,it.message,it.author,it.postTime);
				list.add(msg)
			 }
			 
			 return list
		 
		}
		//返回总页数
		def getTotalPageNum(){
			Sql sql=Sql.newInstance(dbMaps)
			def totalCount=sql.rows("select id from tbl_message").size()
			return (int)totalCount/pageSize
			}
		
		
		 static main(args){
		println	new MessageUtil().listByPage(10);
		}
}
